services:
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/.next
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
  client-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    env_file:
      - .env
