# Use the latest version of node as the base image
FROM node:latest

# Set /app as the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) to the working directory
COPY package*.json ./

# Install the dependencies in the package.json
RUN npm install

# Copy the rest of the application to the working directory
COPY . .

# Expose port 3000 to be accessible from outside the container
EXPOSE 3000

# Run the command "npm run dev" when the container starts
CMD ["npm", "run", "dev"]